code --install-extension antfu.iconify
code --install-extension antfu.open-in-github-button
code --install-extension bradlc.vscode-tailwindcss
code --install-extension charliermarsh.ruff
code --install-extension dbaeumer.vscode-eslint
code --install-extension ddiu8081.moegi-theme
code --install-extension docker.docker
code --install-extension esbenp.prettier-vscode
code --install-extension fabiospampinato.vscode-open-in-github
code --install-extension file-icons.file-icons
code --install-extension github.copilot-chat
code --install-extension github.github-vscode-theme
code --install-extension golang.go
code --install-extension hyoban.tailwindcss-classname-highlight
code --install-extension isudox.vscode-jetbrains-keybindings
code --install-extension ms-azuretools.vscode-containers
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-ceintl.vscode-language-pack-zh-hans
code --install-extension ms-python.debugpy
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-python.vscode-python-envs
code --install-extension naumovs.color-highlight
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension sumneko.lua
code --install-extension usernamehw.errorlens
code --install-extension wakatime.vscode-wakatime
code --install-extension yandeu.five-server
code --install-extension yoavbls.pretty-ts-errors
code --install-extension yzhang.markdown-all-in-one
