code --install-extension angular.ng-template
code --install-extension antfu.iconify
code --install-extension antfu.open-in-github-button
code --install-extension bradlc.vscode-tailwindcss
code --install-extension charliermarsh.ruff
code --install-extension commandcode.commandcode-vscode
code --install-extension dbaeumer.vscode-eslint
code --install-extension ddiu8081.moegi-theme
code --install-extension docker.docker
code --install-extension esbenp.prettier-vscode
code --install-extension fabiospampinato.vscode-open-in-github
code --install-extension file-icons.file-icons
code --install-extension github.github-vscode-theme
code --install-extension github.vscode-pull-request-github
code --install-extension golang.go
code --install-extension hyoban.tailwindcss-classname-highlight
code --install-extension k--kato.intellij-idea-keybindings
code --install-extension llvm-vs-code-extensions.vscode-clangd
code --install-extension loyio.nand2tetris-vscode
code --install-extension miguelsolorio.symbols
code --install-extension ms-azuretools.vscode-containers
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-ceintl.vscode-language-pack-zh-hans
code --install-extension ms-python.debugpy
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-python.vscode-python-envs
code --install-extension ms-vscode.makefile-tools
code --install-extension naumovs.color-highlight
code --install-extension nefrob.vscode-just-syntax
code --install-extension ocamllabs.ocaml-platform
code --install-extension openai.chatgpt
code --install-extension oxc.oxc-vscode
code --install-extension pierrecomputer.pierre-vscode-icons
code --install-extension raillyhugo.one-hunter
code --install-extension raunofreiberg.vesper
code --install-extension redhat.vscode-xml
code --install-extension redhat.vscode-yaml
code --install-extension rust-lang.rust-analyzer
code --install-extension sjhuangx.vscode-scheme
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension sumneko.lua
code --install-extension superant.mc-dp-icons
code --install-extension tamasfe.even-better-toml
code --install-extension tomoki1207.pdf
code --install-extension twxs.cmake
code --install-extension usernamehw.errorlens
code --install-extension vadimcn.vscode-lldb
code --install-extension vitest.explorer
code --install-extension vue.volar
code --install-extension w88975.code-translate
code --install-extension wakatime.vscode-wakatime
code --install-extension yandeu.five-server
code --install-extension yoavbls.pretty-ts-errors
code --install-extension yusifaliyevpro.vscicons
code --install-extension yzhang.markdown-all-in-one
