code --install-extension antfu.file-nesting
code --install-extension antfu.iconify
code --install-extension antfu.icons-carbon
code --install-extension antfu.open-in-github-button
code --install-extension bradlc.vscode-tailwindcss
code --install-extension catppuccin.catppuccin-vsc
code --install-extension catppuccin.catppuccin-vsc-icons
code --install-extension charliermarsh.ruff
code --install-extension codeium.codeium
code --install-extension dbaeumer.vscode-eslint
code --install-extension ddiu8081.moegi-theme
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension evondev.dracula-high-contrast
code --install-extension fabiospampinato.vscode-open-in-github
code --install-extension file-icons.file-icons
code --install-extension franzgollhammer.jb-fleet-dark
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension github.github-vscode-theme
code --install-extension github.vscode-github-actions
code --install-extension github.vscode-pull-request-github
code --install-extension golang.go
code --install-extension hyoban.tailwindcss-classname-highlight
code --install-extension isudox.vscode-jetbrains-keybindings
code --install-extension johnsoncodehk.vscode-tsconfig-helper
code --install-extension miguelsolorio.symbols
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-ceintl.vscode-language-pack-zh-hans
code --install-extension ms-python.debugpy
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension mvllow.rose-pine
code --install-extension naumovs.color-highlight
code --install-extension oderwat.indent-rainbow
code --install-extension piyushsarkar.sort-css-properties
code --install-extension pmndrs.pmndrs
code --install-extension prisma.prisma
code --install-extension raillyhugo.one-hunter
code --install-extension raunofreiberg.vesper
code --install-extension redhat.vscode-xml
code --install-extension rust-lang.rust-analyzer
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension supermaven.supermaven
code --install-extension tamasfe.even-better-toml
code --install-extension trapfether.tailwind-raw-reorder
code --install-extension usernamehw.errorlens
code --install-extension vitest.explorer
code --install-extension vue.volar
code --install-extension wakatime.vscode-wakatime
code --install-extension yandeu.five-server
code --install-extension yoavbls.pretty-ts-errors
code --install-extension yutengjing.package-manager-enhancer
code --install-extension yzhang.markdown-all-in-one
