# code --list-extensions | xargs -L 1 echo code --install-extension
code --install-extension antfu.iconify
code --install-extension antfu.icons-carbon
code --install-extension antfu.open-in-github-button
code --install-extension antfu.theme-vitesse
code --install-extension antfu.where-am-i
code --install-extension bradlc.vscode-tailwindcss
code --install-extension catppuccin.catppuccin-vsc
code --install-extension catppuccin.catppuccin-vsc-icons
code --install-extension dbaeumer.vscode-eslint
code --install-extension ddiu8081.moegi-theme
code --install-extension drcika.apc-extension
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension fabiospampinato.vscode-open-in-github
code --install-extension file-icons.file-icons
code --install-extension github.github-vscode-theme
code --install-extension github.vscode-github-actions
code --install-extension hyoban.tailwindcss-classname-highlight
code --install-extension isudox.vscode-jetbrains-keybindings
code --install-extension johnsoncodehk.vscode-tsconfig-helper
code --install-extension miguelsolorio.symbols
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension naumovs.color-highlight
code --install-extension piyushsarkar.sort-css-properties
code --install-extension pmndrs.pmndrs
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension supermaven.supermaven
code --install-extension tamasfe.even-better-toml
code --install-extension trapfether.tailwind-raw-reorder
code --install-extension usernamehw.errorlens
code --install-extension vue.volar
code --install-extension wakatime.vscode-wakatime
code --install-extension yandeu.five-server
code --install-extension yoavbls.pretty-ts-errors
code --install-extension yzhang.markdown-all-in-one
