code --install-extension angular.ng-template
code --install-extension antfu.file-nesting
code --install-extension antfu.iconify
code --install-extension antfu.open-in-github-button
code --install-extension anysphere.cursorpyright
code --install-extension anysphere.pyright
code --install-extension bierner.lit-html
code --install-extension bradlc.vscode-tailwindcss
code --install-extension charliermarsh.ruff
code --install-extension dbaeumer.vscode-eslint
code --install-extension ddiu8081.moegi-theme
code --install-extension devdojo.alpinejs-syntax-highlight
code --install-extension esbenp.prettier-vscode
code --install-extension fabiospampinato.vscode-open-in-github
code --install-extension franzgollhammer.jb-fleet-dark
code --install-extension github.github-vscode-theme
code --install-extension golang.go
code --install-extension hyoban.tailwindcss-classname-highlight
code --install-extension isudox.vscode-jetbrains-keybindings
code --install-extension jimothythegreat.vscodium-nand2tetris-hdl
code --install-extension lokalise.i18n-ally
code --install-extension mark-wiemer.love2d-made-easy
code --install-extension miguelsolorio.symbols
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.debugpy
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension naumovs.color-highlight
code --install-extension oderwat.indent-rainbow
code --install-extension piyushsarkar.sort-css-properties
code --install-extension prisma.prisma
code --install-extension qwtel.sqlite-viewer
code --install-extension raillyhugo.one-hunter
code --install-extension raunofreiberg.vesper
code --install-extension redhat.vscode-yaml
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension sumneko.lua
code --install-extension tamasfe.even-better-toml
code --install-extension timonwong.shellcheck
code --install-extension tomoki1207.pdf
code --install-extension trapfether.tailwind-raw-reorder
code --install-extension usernamehw.errorlens
code --install-extension vitest.explorer
code --install-extension vue.volar
code --install-extension wakatime.vscode-wakatime
code --install-extension wasp-lang.wasp
code --install-extension wayou.vscode-todo-highlight
code --install-extension yandeu.five-server
code --install-extension yzhang.markdown-all-in-one
