# code --list-extensions | xargs -L 1 echo code --install-extension
code --install-extension angular.ng-template
code --install-extension antfu.iconify
code --install-extension antfu.open-in-github-button
code --install-extension antfu.theme-vitesse
code --install-extension bradlc.vscode-tailwindcss
code --install-extension catppuccin.catppuccin-vsc-icons
code --install-extension cdonohue.quill-icons
code --install-extension charliermarsh.ruff
code --install-extension codeium.codeium
code --install-extension dbaeumer.vscode-eslint
code --install-extension ddiu8081.moegi-theme
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension evondev.dracula-high-contrast
code --install-extension fabiospampinato.vscode-open-in-github
code --install-extension fittentech.fitten-code
code --install-extension franzgollhammer.jb-fleet-dark
code --install-extension github.github-vscode-theme
code --install-extension github.vscode-github-actions
code --install-extension github.vscode-pull-request-github
code --install-extension hyoban.tailwindcss-classname-highlight
code --install-extension isudox.vscode-jetbrains-keybindings
code --install-extension keksiqc.idx-monospace-theme
code --install-extension leetcode.vscode-leetcode
code --install-extension miguelsolorio.symbols
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-ceintl.vscode-language-pack-zh-hans
code --install-extension ms-python.debugpy
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension naumovs.color-highlight
code --install-extension oderwat.indent-rainbow
code --install-extension piyushsarkar.sort-css-properties
code --install-extension pmndrs.pmndrs
code --install-extension prisma.prisma
code --install-extension quick-lint.quick-lint-js
code --install-extension raillyhugo.one-hunter
code --install-extension rangav.vscode-thunder-client
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension tamasfe.even-better-toml
code --install-extension trapfether.tailwind-raw-reorder
code --install-extension usernamehw.errorlens
code --install-extension vue.volar
code --install-extension wakatime.vscode-wakatime
code --install-extension whizkydee.material-palenight-theme
code --install-extension yandeu.five-server
code --install-extension yoavbls.pretty-ts-errors
code --install-extension yrm.type-challenges
code --install-extension yzhang.markdown-all-in-one
