# code --list-extensions | xargs -L 1 echo code --install-extension
code --install-extension antfu.file-nesting
code --install-extension antfu.iconify
code --install-extension antfu.open-in-github-button
code --install-extension bradlc.vscode-tailwindcss
code --install-extension charliermarsh.ruff
code --install-extension dbaeumer.vscode-eslint
code --install-extension ddiu8081.moegi-theme
code --install-extension esbenp.prettier-vscode
code --install-extension fabiospampinato.vscode-open-in-github
code --install-extension file-icons.file-icons
code --install-extension hyoban.tailwindcss-classname-highlight
code --install-extension ms-ceintl.vscode-language-pack-zh-hans
code --install-extension ms-python.debugpy
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension qwtel.sqlite-viewer
code --install-extension tamasfe.even-better-toml
code --install-extension trapfether.tailwind-raw-reorder
code --install-extension vue.volar
code --install-extension wakatime.vscode-wakatime
